#!/bin/bash
# Build the two-instance payroll-sync test bed:
#
#   sync_master  (role=master)  <--- HTTP --->  sync_client  (role=client)
#
# Each database runs in its own Odoo container on the shared docker network, so
# the traffic between them is real HTTP over real sockets, not an in-process
# shortcut. Credentials are generated here and written to creds.env for
# run-tests.sh to reuse.
#
#   ./setup.sh                 full rebuild of both databases
#   ./setup.sh --no-rebuild    keep the databases, just rewire and restart

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

CREDS="$HERE/creds.env"
REBUILD=true
for arg in "$@"; do
  [[ "$arg" == "--no-rebuild" ]] && REBUILD=false
done

# Hands a JSON argument file to the next `odoo shell` snippet. The container
# cannot see host environment variables, so arguments travel through a file.
put_args() {
  local db="$1" json="$2"
  printf '%s' "$json" | docker exec -i "$CONTAINER" tee /tmp/sync_e2e_args.json >/dev/null
}

run_py() {
  # run_py <db> <script-name> ; echoes the script's stdout
  local db="$1" script="$2"
  odoo_shell "$db" < "$HERE/py/$script" 2>/dev/null | tr -d '\r'
}

echo "=============================================="
echo " Payroll sync — test bed"
echo "  master: $MASTER_DB  -> $MASTER_URL"
echo "  client: $CLIENT_DB  -> $CLIENT_URL"
echo "=============================================="

if [[ "$REBUILD" == "true" ]]; then
  echo "[1/5] Creating both databases and installing the module..."
  stop_servers
  for db in "$MASTER_DB" "$CLIENT_DB"; do
    drop_db "$db"
    # Match Odoo's own log lines only: docutils writes "(ERROR/3) ..." while
    # rendering the manifest description, which is not an install failure.
    if odoo_cli "$db" --without-demo=all --log-level=warn --stop-after-init --no-http \
         -i l10n_do_hr_payroll_sync 2>&1 | grep -E "(CRITICAL|ERROR) $db|Traceback \(most recent"; then
      echo "ERROR: install failed on $db" >&2; exit 1
    fi
    echo "   $db ready"
  done
else
  echo "[1/5] Reusing the existing databases (--no-rebuild)."
  stop_servers
fi

echo "[2/5] Client: setting role and minting its inbound key..."
put_args "$CLIENT_DB" '{}'
CLIENT_INBOUND_KEY="$(run_py "$CLIENT_DB" setup_client.py | grep '^KEY=' | cut -d= -f2- || true)"
[[ -z "$CLIENT_INBOUND_KEY" ]] && { echo "ERROR: no client inbound key generated" >&2; exit 1; }
echo "   client inbound key ready"

echo "[3/5] Master: setting role, registering the client, minting its own key..."
put_args "$MASTER_DB" "$(printf '{"client_url": "%s", "client_key": "%s"}' \
  "$CLIENT_INTERNAL_URL" "$CLIENT_INBOUND_KEY")"
MASTER_OUT="$(run_py "$MASTER_DB" setup_master.py || true)"
MASTER_INBOUND_KEY="$(printf '%s' "$MASTER_OUT" | grep '^KEY=' | cut -d= -f2- || true)"
SYNC_CLIENT_ID="$(printf '%s' "$MASTER_OUT" | grep '^CLIENT_ID=' | cut -d= -f2- || true)"
[[ -z "$MASTER_INBOUND_KEY" ]] && { echo "ERROR: no master inbound key generated" >&2; exit 1; }
echo "   master inbound key ready, client record #$SYNC_CLIENT_ID"

echo "[4/5] Client: pointing pull mode back at the master..."
put_args "$CLIENT_DB" "$(printf '{"master_url": "%s", "master_key": "%s"}' \
  "$MASTER_INTERNAL_URL" "$MASTER_INBOUND_KEY")"
[[ "$(run_py "$CLIENT_DB" store_master_key.py | grep -c '^OK$')" == "1" ]] \
  || { echo "ERROR: could not store the master credentials on the client" >&2; exit 1; }

cat > "$CREDS" <<EOF
# Generated by setup.sh — credentials for the payroll-sync test bed.
CLIENT_INBOUND_KEY='$CLIENT_INBOUND_KEY'
MASTER_INBOUND_KEY='$MASTER_INBOUND_KEY'
SYNC_CLIENT_ID='$SYNC_CLIENT_ID'
EOF
echo "   credentials written to $CREDS"

echo "[5/5] Starting both servers..."
start_server "$MASTER_NAME" "$MASTER_DB" "$MASTER_PORT"
start_server "$CLIENT_NAME" "$CLIENT_DB" "$CLIENT_PORT"
wait_http "$MASTER_URL" || { echo "ERROR: master did not come up"; docker logs "$MASTER_NAME" 2>&1 | tail -30; exit 1; }
wait_http "$CLIENT_URL" || { echo "ERROR: client did not come up"; docker logs "$CLIENT_NAME" 2>&1 | tail -30; exit 1; }

echo ""
echo "Test bed up."
echo "  master  $MASTER_URL   (admin/admin)"
echo "  client  $CLIENT_URL   (admin/admin)"
echo "Run the scenarios with:  tools/sync-e2e/run-tests.sh"
echo "Tear down with:          tools/sync-e2e/teardown.sh"
